apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasg-deployment
  labels:
    app: tasg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasg
  template:
    metadata:
      labels:
        app: tasg
    spec:
      automountServiceAccountToken: false
      containers:
        - name: tasg-frontend
          image: gmarinho21/tasg:48a82d5
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 200m
              memory: 300Mi
              ephemeral-storage: 2Gi
            limits:
              cpu: 300m
              memory: 500Mi
              ephemeral-storage: 3Gi
          env:
            - name: VITE_BACKEND_URL
              valueFrom:
                secretKeyRef:
                  name: tasg-frontend-secret
                  key: VITE_BACKEND_URL
