apiVersion: apps/v1
kind: Deployment

metadata:
  name: tasg-deployment
  labels:
    app: tasg

spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasg
  template:
    metadata:
      labels:
        app: tasg
    spec:
      containers:
        - name: tasg-frontend
          image: gmarinho21/tasg:a093068
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 200m
              memory: 300Mi
            limits:
              cpu: 300m
              memory: 500Mi
        env:
        - name: tasg-backend-secret
          valueFrom:
            configMapKeyRef:
              name: PORT
              key: tasg-backend-secret
        - name: tasg-backend-secret
          valueFrom:
            configMapKeyRef:
              name: JWT_SECRET
              key: tasg-backend-secret
        - name: tasg-backend-secret
          valueFrom:
            configMapKeyRef:
              name: DB_USER
              key: tasg-backend-secret
        - name: tasg-backend-secret
          valueFrom:
            configMapKeyRef:
              name: DB_PASSWORD
              key: tasg-backend-secret
        - name: tasg-backend-secret
          valueFrom:
            configMapKeyRef:
              name: DB_PATH
              key: tasg-backend-secret
        - name: tasg-backend-secret
          valueFrom:
            configMapKeyRef:
              name: RESEND_API_KEY
              key: tasg-backend-secret                                                                      