apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: tasg-rollout-bluegreen
  namespace: tasg
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: tasg-rollout
  template:
    metadata:
      labels:
        app: tasg-rollout
    spec:
      automountServiceAccountToken: false
      containers:
        - name: tasg-frontend
          image: gmarinho21/tasg:30222d9
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 200m
              memory: 300Mi
              ephemeral-storage: 2Gi
            limits:
              cpu: 300m
              memory: 500Mi
              ephemeral-storage: 3Gi
          env:
            - name: VITE_BACKEND_URL
              valueFrom:
                secretKeyRef:
                  name: tasg-frontend-secret
                  key: VITE_BACKEND_URL
  strategy:
    blueGreen:
      activeService: tasg-rollout-frontend-service-active
      previewService: tasg-rollout-frontend-service-preview
      autoPromotionEnabled: false
