apiVersion: v1
kind: Service
metadata:
  name: tasg-rollout-frontend-service-active
  namespace: tasg
spec:
  ports:
    - port: 8181
      targetPort: 80
  selector:
    app: tasg-rollout
---
apiVersion: v1
kind: Service
metadata:
  name: tasg-rollout-frontend-service-preview
  namespace: tasg
spec:
  ports:
    - port: 8181
      targetPort: 80
  selector:
    app: tasg-rollout
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: tasg-rollout-ingress-active
  namespace: tasg
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`tasg.preview.gabrielm.com.br`)
      services:
        - kind: Service
          name: tasg-rollout-frontend-service-active
          port: 8181
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: tasg-rollout-ingress-preview
  namespace: tasg
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`tasg.dev.gabrielm.com.br`)
      services:
        - kind: Service
          name: tasg-rollout-frontend-service-preview
          port: 8181
