name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    if: ${{ !contains(github.event.head_commit.message, 'Update tag in values helm') }}
    name: "Build and Push"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            gmarinho21/tasg:${{ steps.generate_sha.outputs.sha}}
            gmarinho21/tasg:latest
          secret-envs: |
            VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }}

      - name: Ensure Branch Exists
        run: |
          echo "Checking if branch exists..."
          BRANCH=release  # Define your branch here
          git fetch origin
          if git branch -r | grep -w "origin/$BRANCH"; then
            echo "Branch '$BRANCH' already exists."
          else
            echo "Branch '$BRANCH' does not exist. Creating it..."
            git checkout -b $BRANCH
            git push origin $BRANCH
          fi

      - name: Update image deployment
        uses: fjogeleit/yaml-update-action@main
        with:
          branch: release
          targetBranch: main
          createPR: true
          valueFile: "k8s/deployment.yaml"
          propertyPath: "spec.template.spec.containers[0].image"
          value: gmarinho21/tasg:${{ steps.generate_sha.outputs.sha }}
          commitChange: true
          message: "[skip ci] Update tag in values helm"
          token: ${{ secrets.GITHUB_TOKEN }}
